import type { PRDiff, PRReview, PRSummary } from '@devlens/core'

const REVIEW_SYSTEM_PROMPT = `You are an expert senior software engineer performing a thorough code review.
Analyze the provided PR diff and return a structured JSON review.
Be specific, actionable, and cite exact file names and line numbers where possible.
Focus on real issues — avoid nitpicking minor style preferences unless they impact readability significantly.`

const SUMMARY_SYSTEM_PROMPT = `You are a technical writer helping engineering teams understand code changes.
Analyze the provided PR and return a structured JSON summary that helps reviewers quickly understand the change.`

/**
 * Build the prompt for a PR review.
 */
export function buildReviewPrompt(diff: PRDiff): string {
  const filesSummary = diff.files
    .map((f) => `### ${f.filename} (+${f.additions} -${f.deletions})\n\`\`\`diff\n${f.patch}\n\`\`\``)
    .join('\n\n')

  return `Review the following Pull Request and return a JSON object matching this exact schema:

{
  "summary": "2-3 sentence overview of what this PR does",
  "riskLevel": "low" | "medium" | "high",
  "sections": {
    "bugs": [{ "file": string, "line": number | null, "severity": "info"|"warning"|"error", "message": string, "suggestion": string | null }],
    "security": [...same shape...],
    "performance": [...same shape...],
    "style": [...same shape...]
  },
  "overallFeedback": "Constructive overall feedback paragraph"
}

PR Title: ${diff.title}
Author: ${diff.author}
Base ← Head: ${diff.baseBranch} ← ${diff.headBranch}
Description: ${diff.description || '(none)'}
Total: +${diff.additions} -${diff.deletions}

${filesSummary}

Return only valid JSON. No markdown code blocks.`
}

export function buildReviewSystemPrompt(): string {
  return REVIEW_SYSTEM_PROMPT
}

/**
 * Build the prompt for a PR summary.
 */
export function buildSummaryPrompt(diff: PRDiff): string {
  const filesList = diff.files.map((f) => `- ${f.filename} (${f.status})`).join('\n')

  return `Summarize the following Pull Request and return a JSON object matching this exact schema:

{
  "whatChanged": "Clear description of what was changed",
  "whyItMatters": "Why this change is important or what problem it solves",
  "riskLevel": "low" | "medium" | "high",
  "testingChecklist": ["item1", "item2", ...],
  "breakingChanges": true | false,
  "breakingChangesDescription": "Description if breaking, null otherwise"
}

PR Title: ${diff.title}
Author: ${diff.author}
Description: ${diff.description || '(none)'}
Total: +${diff.additions} -${diff.deletions}

Files changed:
${filesList}

Return only valid JSON. No markdown code blocks.`
}

export function buildSummarySystemPrompt(): string {
  return SUMMARY_SYSTEM_PROMPT
}

/**
 * Parse AI response into a PRReview object.
 */
export function parseReviewResponse(raw: string): PRReview {
  try {
    return JSON.parse(raw) as PRReview
  } catch {
    // If JSON parsing fails, return a graceful fallback
    return {
      summary: raw.slice(0, 500),
      riskLevel: 'medium',
      sections: { bugs: [], security: [], performance: [], style: [] },
      overallFeedback: raw,
    }
  }
}

/**
 * Parse AI response into a PRSummary object.
 */
export function parseSummaryResponse(raw: string): PRSummary {
  try {
    return JSON.parse(raw) as PRSummary
  } catch {
    return {
      whatChanged: raw.slice(0, 300),
      whyItMatters: 'Could not parse structured summary.',
      riskLevel: 'medium',
      testingChecklist: [],
      breakingChanges: false,
    }
  }
}

/**
 * Format a PRReview into a GitHub-flavoured markdown comment.
 */
export function formatReviewAsComment(review: PRReview): string {
  const riskEmoji = { low: '🟢', medium: '🟡', high: '🔴' }[review.riskLevel]
  const severityEmoji = { info: 'ℹ️', warning: '⚠️', error: '❌' }

  const formatSection = (title: string, items: PRReview['sections']['bugs']) => {
    if (items.length === 0) return `### ${title}\n✅ No issues found.\n`
    return `### ${title}\n${items
      .map(
        (i) =>
          `${severityEmoji[i.severity]} **${i.file ?? 'General'}${i.line ? `:${i.line}` : ''}** — ${i.message}${i.suggestion ? `\n   > 💡 ${i.suggestion}` : ''}`,
      )
      .join('\n')}\n`
  }

  return `## 🔍 DevLens Code Review

${riskEmoji} **Risk Level:** ${review.riskLevel.toUpperCase()}

**Summary:** ${review.summary}

---

${formatSection('🐛 Bugs', review.sections.bugs)}
${formatSection('🔐 Security', review.sections.security)}
${formatSection('⚡ Performance', review.sections.performance)}
${formatSection('🎨 Style', review.sections.style)}

---

### Overall Feedback
${review.overallFeedback}

---
*Generated by [DevLens](https://github.com/devlens/devlens) — AI-powered code review*`
}

/**
 * Format a PRSummary into a GitHub-flavoured markdown comment.
 */
export function formatSummaryAsComment(summary: PRSummary): string {
  const riskEmoji = { low: '🟢', medium: '🟡', high: '🔴' }[summary.riskLevel]

  return `## 📋 DevLens PR Summary

### What Changed
${summary.whatChanged}

### Why It Matters
${summary.whyItMatters}

${riskEmoji} **Risk Level:** ${summary.riskLevel.toUpperCase()}
${summary.breakingChanges ? `\n⚠️ **Breaking Changes:** ${summary.breakingChangesDescription}\n` : ''}

### Testing Checklist
${summary.testingChecklist.map((item) => `- [ ] ${item}`).join('\n')}

---
*Generated by [DevLens](https://github.com/devlens/devlens)*`
}
